name: Create Daily Challenge

on:
  schedule:
    - cron: 5 * * * *      # every 5 mins
    # - cron: 0 8 * * *       # every day at 8am

  workflow_dispatch:

jobs:
  run-challenge-creation-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run script
        env:
            API_URL_PROD: ${{ secrets.API_URL_PROD }}
        run: |
          python scripts/add_random_challenge.py
